let products = [
    // Smartphones (1–25)
    {
      id: 1,
      brand: 'Apple',
      name: 'iPhone 15 Pro Max',
      description: 'Apple’s latest flagship with A17 Pro chip and titanium design.',
      price: '₹1,59,900',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 2,
      brand: 'Samsung',
      name: 'Galaxy S24 Ultra',
      description: '6.8" QHD+ AMOLED, Snapdragon 8 Gen 3, 200MP camera.',
      price: '₹1,29,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 3,
      brand: 'Xiaomi',
      name: '14 Pro',
      description: 'Leica optics, Snapdragon 8 Gen 3, fast charging.',
      price: '₹69,999',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 4,
      brand: 'Vivo',
      name: 'X100 Pro',
      description: 'Flagship camera and performance at value pricing.',
      price: '₹89,999',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 5,
      brand: 'OnePlus',
      name: '12',
      description: 'Powerful performance with clean UI and 100W fast charging.',
      price: '₹64,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 6,
      brand: 'Realme',
      name: 'GT 3 Pro',
      description: 'Snapdragon 8 Gen 3, 120Hz AMOLED display, 50MP camera.',
      price: '₹55,000',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 7,
      brand: 'Google',
      name: 'Pixel 9 Pro',
      description: 'Tensor G3 chip, 6.7" OLED display, 50MP camera.',
      price: '₹89,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 8,
      brand: 'Samsung',
      name: 'Galaxy Z Fold 5',
      description: 'Foldable 7.6" display, multitasking pro device.',
      price: '₹1,49,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 9,
      brand: 'Motorola',
      name: 'Edge 50 Fusion',
      description: 'Clean Android, OLED screen, Dolby Atmos speakers.',
      price: '₹39,999',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 10,
      brand: 'Infinix',
      name: 'Zero 30',
      description: 'Affordable powerhouse with 108MP camera.',
      price: '₹22,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 11,
      brand: 'Lava',
      name: 'Agni 2 5G',
      description: 'Indian brand with MediaTek Dimensity 7050 and curved display.',
      price: '₹19,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 12,
      brand: 'iQOO',
      name: 'Neo 7 Pro',
      description: 'Gaming-focused phone with Snapdragon 8+ Gen 1.',
      price: '₹34,999',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 13,
      brand: 'Poco',
      name: 'F5 5G',
      description: 'Value-for-money flagship killer with AMOLED screen.',
      price: '₹28,999',
      deliveryEstimate: '2-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 14,
      brand: 'Sony',
      name: 'Xperia 1 V',
      description: 'Professional-grade cameras and 4K OLED display.',
      price: '₹1,20,000',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 15,
      brand: 'Asus',
      name: 'ROG Phone 8',
      description: 'Ultimate gaming phone with shoulder triggers and AMOLED screen.',
      price: '₹74,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 16,
      brand: 'Nothing',
      name: 'Phone (2)',
      description: 'Unique transparent design and clean Android experience.',
      price: '₹44,999',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 17,
      brand: 'Tecno',
      name: 'Phantom X2',
      description: 'Flagship features at affordable price with curved display.',
      price: '₹36,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 18,
      brand: 'Honor',
      name: 'Magic 6 Pro',
      description: 'Premium specs and AI camera tuning.',
      price: '₹89,000',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 19,
      brand: 'Realme',
      name: '11x 5G',
      description: 'Budget-friendly 5G device with 64MP camera.',
      price: '₹13,499',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 20,
      brand: 'Micromax',
      name: 'IN Note 2',
      description: 'Indian-made phone with AMOLED display under ₹15k.',
      price: '₹12,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 21,
      brand: 'Oppo',
      name: 'Reno 11 Pro',
      description: 'Flagship-like design and camera in midrange segment.',
      price: '₹35,999',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 22,
      brand: 'Infinix',
      name: 'GT 10 Pro',
      description: 'Gaming-centric phone with RGB lights and unique design.',
      price: '₹17,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 5 days.',
      status: 'In Stock',
    },
    {
      id: 23,
      brand: 'HTC',
      name: 'U23 Pro',
      description: 'Comes with clean UI, OLED screen, and a 108MP camera.',
      price: '₹49,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 24,
      brand: 'Realme',
      name: 'C55',
      description: 'Budget-friendly device with decent specs and Dynamic Island-style UI.',
      price: '₹10,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 25,
      brand: 'iQOO',
      name: '12 5G',
      description: 'Snapdragon 8 Gen 3, 144Hz AMOLED display, 5000mAh battery, 120W fast charging.',
      price: '₹52,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
  
  
    // Laptops (26–50)
    {
      id: 26,
      brand: 'HP',
      name: 'Spectre x360',
      description: 'Premium 2-in-1 laptop with Intel i7 and OLED display.',
      price: '₹1,39,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 27,
      brand: 'Lenovo',
      name: 'Legion 5 Pro',
      description: 'Gaming beast with Ryzen 7, RTX 4070, and QHD display.',
      price: '₹1,49,000',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 28,
      brand: 'ASUS',
      name: 'Zenbook 14 OLED',
      description: 'Ultra-thin, lightweight with stunning OLED display.',
      price: '₹94,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 29,
      brand: 'Dell',
      name: 'XPS 13',
      description: 'Premium ultraportable with Intel Core i7, 13.3" display, and excellent battery life.',
      price: '₹1,19,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 30,
      brand: 'Apple',
      name: 'MacBook Pro 14',
      description: 'Apple M1 Pro chip with 16GB RAM, 512GB SSD, and 14-inch Retina display.',
      price: '₹1,94,900',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 14 days.',
      status: 'In Stock',
    },
    // Laptops (31-50)
    {
      id: 31,
      brand: 'Acer',
      name: 'Swift 3',
      description: 'Lightweight laptop with Ryzen 7, 8GB RAM, and 512GB SSD.',
      price: '₹59,999',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 32,
      brand: 'HP',
      name: 'Envy x360',
      description: '2-in-1 laptop with Intel i7, 16GB RAM, and 512GB SSD.',
      price: '₹94,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 33,
      brand: 'Lenovo',
      name: 'IdeaPad Slim 5',
      description: 'Budget-friendly laptop with Ryzen 5, 8GB RAM, and 512GB SSD.',
      price: '₹55,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 34,
      brand: 'MSI',
      name: 'GE76 Raider',
      description: 'Gaming laptop with Intel i9, RTX 3080, and 17.3" 144Hz display.',
      price: '₹2,29,999',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 35,
      brand: 'Asus',
      name: 'TUF Gaming F15',
      description: 'Affordable gaming laptop with Ryzen 7, RTX 3060, and 144Hz display.',
      price: '₹89,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 36,
      brand: 'Dell',
      name: 'Alienware X17',
      description: 'Premium gaming laptop with Intel i9, RTX 3080, and 17.3" display.',
      price: '₹3,29,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 37,
      brand: 'HP',
      name: 'Pavilion x360',
      description: 'Convertible laptop with Intel i5, 8GB RAM, and 512GB SSD.',
      price: '₹59,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 38,
      brand: 'Microsoft',
      name: 'Surface Laptop 4',
      description: '13.5-inch touchscreen, Intel i7, 16GB RAM, and 512GB SSD.',
      price: '₹1,09,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 39,
      brand: 'Razer',
      name: 'Blade 15 Advanced',
      description: 'Slim gaming laptop with Intel i7, RTX 3070, and 15.6" 144Hz display.',
      price: '₹2,19,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 40,
      brand: 'Gigabyte',
      name: 'AORUS 15G',
      description: 'Gaming laptop with Intel i7, RTX 3060, and 15.6" display.',
      price: '₹1,39,999',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 41,
      brand: 'HP',
      name: 'Omen 15',
      description: 'Gaming laptop with Ryzen 9, RTX 3070, and 15.6" display.',
      price: '₹1,79,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 42,
      brand: 'Asus',
      name: 'ZenBook Flip 14',
      description: 'Convertible laptop with Intel i5, 8GB RAM, and 512GB SSD.',
      price: '₹69,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 43,
      brand: 'Apple',
      name: 'MacBook Air M2',
      description: 'Apple M2 chip, 8GB RAM, 256GB SSD, and 13.6-inch display.',
      price: '₹1,19,900',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 14 days.',
      status: 'In Stock',
    },
    {
      id: 44,
      brand: 'Dell',
      name: 'Inspiron 15 5000',
      description: 'Budget laptop with Intel i5, 8GB RAM, and 512GB SSD.',
      price: '₹59,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 45,
      brand: 'Lenovo',
      name: 'ThinkPad X1 Carbon',
      description: 'Business laptop with Intel i7, 16GB RAM, and 512GB SSD.',
      price: '₹1,49,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 46,
      brand: 'HP',
      name: 'Elite Dragonfly',
      description: 'Business ultrabook with Intel i7, 16GB RAM, and 512GB SSD.',
      price: '₹1,79,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 47,
      brand: 'Asus',
      name: 'ROG Strix G17',
      description: 'Gaming laptop with Ryzen 9, RTX 3070, and 17.3" display.',
      price: '₹1,89,999',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 48,
      brand: 'Acer',
      name: 'Predator Helios 300',
      description: 'High-end gaming laptop with Intel i7, RTX 3070, and 15.6" display.',
      price: '₹1,59,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 49,
      brand: 'MSI',
      name: 'Stealth 15M',
      description: 'Slim gaming laptop with Intel i7, RTX 3060, and 15.6" display.',
      price: '₹1,39,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 50,
      brand: 'Samsung',
      name: 'Galaxy Book Pro 360',
      description: '2-in-1 laptop with Intel i5, 8GB RAM, and 512GB SSD.',
      price: '₹79,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
  
    // TVs (51–65)
    {
      id: 51,
      brand: 'Samsung',
      name: 'Crystal 4K UHD Smart TV',
      description: '43-inch 4K UHD TV with HDR, Crystal Processor 4K.',
      price: '₹32,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 52,
      brand: 'LG',
      name: 'OLED55CXPTA',
      description: '55-inch 4K OLED TV with Dolby Vision IQ and Dolby Atmos.',
      price: '₹1,29,990',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 14 days.',
      status: 'Limited Stock',
    },
    {
      id: 53,
      brand: 'Sony',
      name: 'Bravia X90J',
      description: '55-inch 4K UHD Smart TV with Full Array LED and Google Assistant.',
      price: '₹94,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 54,
      brand: 'Samsung',
      name: 'QLED 4K Smart TV',
      description: '65-inch QLED 4K TV with Quantum Dot and 100% Color Volume.',
      price: '₹1,39,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 55,
      brand: 'TCL',
      name: 'P8M 4K UHD Smart TV',
      description: '55-inch 4K UHD with Dolby Audio, Android TV, and Google Assistant.',
      price: '₹37,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 56,
      brand: 'LG',
      name: 'NanoCell 65NANO80TNA',
      description: '65-inch 4K NanoCell Smart TV with AI ThinQ and Dolby Vision.',
      price: '₹78,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 57,
      brand: 'Samsung',
      name: 'The Frame QLED 4K TV',
      description: '55-inch QLED TV with Art Mode and customizable bezels.',
      price: '₹1,19,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 58,
      brand: 'Sony',
      name: 'Bravia XR A80J OLED',
      description: '55-inch 4K OLED TV with Cognitive Processor XR and Google Assistant.',
      price: '₹1,39,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 59,
      brand: 'Mi',
      name: 'Mi TV 4X 50-inch',
      description: '50-inch 4K UHD Android TV with PatchWall and Google Assistant.',
      price: '₹29,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 60,
      brand: 'Samsung',
      name: 'Smart LED TV',
      description: '32-inch HD Ready LED TV with Smart Hub and Wi-Fi connectivity.',
      price: '₹18,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 61,
      brand: 'OnePlus',
      name: 'OnePlus TV Q1 55-inch',
      description: '55-inch 4K QLED TV with Dolby Vision and Dolby Atmos.',
      price: '₹69,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 62,
      brand: 'Vizio',
      name: 'V-Series 50-inch 4K Smart TV',
      description: '50-inch 4K UHD TV with Smartcast and Alexa built-in.',
      price: '₹34,990',
      deliveryEstimate: '3-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 63,
      brand: 'Samsung',
      name: 'TU8000 Crystal UHD TV',
      description: '50-inch Crystal UHD TV with 4K and Smart features.',
      price: '₹38,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 64,
      brand: 'LG',
      name: 'OLED65CXPTA',
      description: '65-inch 4K OLED Smart TV with Dolby Atmos and AI Picture Pro.',
      price: '₹1,79,990',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 14 days.',
      status: 'Limited Stock',
    },
    {
      id: 65,
      brand: 'Philips',
      name: 'Ambilight 4K UHD Smart TV',
      description: '55-inch 4K UHD TV with Ambilight and Google Assistant.',
      price: '₹72,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
  
    // Earbuds (66–85)
    {
      id: 66,
      brand: 'Sony',
      name: 'WF-1000XM4',
      description: 'True wireless noise-cancelling earbuds with long battery life.',
      price: '₹18,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 67,
      brand: 'Apple',
      name: 'AirPods Pro 2nd Gen',
      description: 'Active Noise Cancellation with transparency mode and spatial audio.',
      price: '₹24,900',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 68,
      brand: 'JBL',
      name: 'Tune 125TWS',
      description: 'True wireless earbuds with JBL Deep Bass Sound and 32 hours of playtime.',
      price: '₹4,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 69,
      brand: 'boAt',
      name: 'Airdopes 441',
      description: 'Truly wireless earbuds with IPX7 water resistance and 25 hours of playtime.',
      price: '₹1,799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 70,
      brand: 'Realme',
      name: 'Realme Buds Air 2',
      description: 'Active Noise Cancellation with 25 hours of playback.',
      price: '₹3,299',
      deliveryEstimate: '2-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 71,
      brand: 'Oppo',
      name: 'Enco X',
      description: 'True wireless earbuds with dual drivers and active noise cancellation.',
      price: '₹8,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 72,
      brand: 'Sennheiser',
      name: 'Momentum True Wireless 2',
      description: 'High-fidelity sound with active noise cancellation and up to 28 hours of battery life.',
      price: '₹24,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 73,
      brand: 'Samsung',
      name: 'Galaxy Buds Pro',
      description: 'True wireless earbuds with active noise cancellation and long battery life.',
      price: '₹15,990',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 74,
      brand: 'Xiaomi',
      name: 'Mi True Wireless Earphones 2C',
      description: 'Dual mic environmental noise cancellation with up to 20 hours of playback.',
      price: '₹1,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 75,
      brand: 'boAt',
      name: 'Airdopes 621',
      description: 'Truly wireless earbuds with IPX7 rating, 40 hours playtime, and fast charging.',
      price: '₹2,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 76,
      brand: 'JBL',
      name: 'Live 300TWS',
      description: 'True wireless earbuds with JBL Signature Sound and 20 hours playtime.',
      price: '₹6,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 77,
      brand: 'Realme',
      name: 'Realme Buds Q2',
      description: 'True wireless earbuds with active noise cancellation and long battery life.',
      price: '₹2,499',
      deliveryEstimate: '2-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 78,
      brand: 'OnePlus',
      name: 'Buds Pro',
      description: 'Noise cancelling earbuds with Dolby Atmos support and long battery life.',
      price: '₹9,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 79,
      brand: 'Soundcore',
      name: 'Liberty Air 2 Pro',
      description: 'True wireless earbuds with active noise cancellation and high-quality sound.',
      price: '₹7,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 80,
      brand: 'Bose',
      name: 'QuietComfort Earbuds',
      description: 'Noise-cancelling earbuds with premium sound and up to 6 hours of playtime.',
      price: '₹24,500',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
  
    // Wired Earphones (81–90)
    {
      id: 81,
      brand: 'Sony',
      name: 'MDR-EX150AP',
      description: 'In-ear wired earphones with a high-quality microphone and tangle-free design.',
      price: '₹799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 82,
      brand: 'JBL',
      name: 'C100SI',
      description: 'In-ear wired earphones with powerful bass and one-button universal remote.',
      price: '₹599',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 83,
      brand: 'boAt',
      name: 'Bassheads 100',
      description: 'Wired earphones with deep bass and universal compatibility.',
      price: '₹399',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 84,
      brand: 'Sennheiser',
      name: 'CX 180',
      description: 'Wired earphones with clear, detailed sound and noise isolation.',
      price: '₹999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 85,
      brand: 'Samsung',
      name: 'In-ear Wired Earphones',
      description: 'Wired earphones with noise isolation and crystal-clear audio.',
      price: '₹699',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 86,
      brand: 'Xiaomi',
      name: 'Mi In-Ear Headphones Basic',
      description: 'Wired earphones with dynamic bass and one-button remote.',
      price: '₹399',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 87,
      brand: 'Philips',
      name: 'SHE3205BK',
      description: 'Wired in-ear earphones with noise isolation and balanced sound.',
      price: '₹699',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 88,
      brand: 'Realme',
      name: 'Realme Buds 2',
      description: 'Wired earphones with deep bass and premium finish.',
      price: '₹599',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 89,
      brand: 'boAt',
      name: 'Bassheads 225',
      description: 'Wired earphones with extra bass and tangle-free design.',
      price: '₹599',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 90,
      brand: 'Sony',
      name: 'MDR-EX155AP',
      description: 'Wired earphones with a built-in mic and extra bass.',
      price: '₹799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
  
    // Neckbands (91–120)
    {
      id: 91,
      brand: 'boAt',
      name: 'Rockerz 255',
      description: 'Wireless neckband with 6 hours of playtime and IPX5 water resistance.',
      price: '₹1,299',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 92,
      brand: 'OnePlus',
      name: 'Bullets Wireless Z',
      description: 'Wireless neckband with Warp Charge and up to 20 hours of playtime.',
      price: '₹1,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 93,
      brand: 'JBL',
      name: 'T205BT',
      description: 'Wireless neckband with JBL Pure Bass and 6 hours of playtime.',
      price: '₹1,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 94,
      brand: 'Realme',
      name: 'Realme Buds Wireless 2',
      description: 'Wireless neckband with 25 hours of playtime and active noise cancellation.',
      price: '₹2,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 95,
      brand: 'boAt',
      name: 'Rockerz 330',
      description: 'Neckband with 10 hours of playtime and IPX5 rating.',
      price: '₹1,799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 96,
      brand: 'Xiaomi',
      name: 'Mi Neckband Bluetooth Earphones Pro',
      description: 'Wireless neckband with 20 hours playtime and noise cancellation.',
      price: '₹1,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 97,
      brand: 'Sony',
      name: 'WI-SP510',
      description: 'Wireless neckband with IPX5 rating and 15 hours of battery life.',
      price: '₹2,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 98,
      brand: 'Noise',
      name: 'Sense Neckband',
      description: 'Wireless neckband with 10mm drivers and up to 12 hours playtime.',
      price: '₹1,799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 99,
      brand: 'Oppo',
      name: 'Oppo Enco M32',
      description: 'Wireless neckband with 28 hours of battery life and fast charging.',
      price: '₹1,599',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 100,
      brand: 'Samsung',
      name: 'U Flex',
      description: 'Wireless neckband with 11 hours of playtime and great sound quality.',
      price: '₹1,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
  
    // Home Appliances (101–130)
    {
      id: 101,
      brand: 'Philips',
      name: 'Air Fryer HD9200/90',
      description: 'Healthy air fryer with rapid air technology for crispy and delicious dishes.',
      price: '₹9,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 102,
      brand: 'Dyson',
      name: 'V11 Absolute Pro Cordless Vacuum',
      description: 'Powerful vacuum with intelligent suction and up to 60 minutes of runtime.',
      price: '₹49,900',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 103,
      brand: 'LG',
      name: 'LG 6.5 kg Front Load Washing Machine',
      description: 'Inverter direct drive with 6 motion technology for efficient cleaning.',
      price: '₹28,990',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 104,
      brand: 'Samsung',
      name: 'Samsung 1.5 Ton 5 Star Inverter Split AC',
      description: 'Energy-efficient air conditioner with fast cooling and 5-star rating.',
      price: '₹39,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'Limited Stock',
    },
    {
      id: 105,
      brand: 'Philips',
      name: 'Electric Kettle HD9306/06',
      description: 'Quick boil kettle with automatic shut-off and stainless steel body.',
      price: '₹1,299',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 106,
      brand: 'Preethi',
      name: 'Chefpro Mixer Grinder',
      description: 'Powerful 750W mixer grinder with multiple jars for diverse blending needs.',
      price: '₹3,199',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 107,
      brand: 'Sony',
      name: 'Xperia 5 II',
      description: 'Flagship smartphone with stunning OLED display and 4K recording.',
      price: '₹69,999',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 108,
      brand: 'Samsung',
      name: 'Samsung Galaxy Watch 4',
      description: 'Smartwatch with health tracking, body composition analysis, and fitness features.',
      price: '₹17,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 109,
      brand: 'Whirlpool',
      name: '240 L Frost Free Double Door Refrigerator',
      description: 'Frost-free cooling, energy efficient with easy to clean shelves.',
      price: '₹24,990',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 110,
      brand: 'Mi',
      name: 'Mi Robot Vacuum-Mop P',
      description: 'Smart robot vacuum with mopping function, multiple cleaning modes.',
      price: '₹19,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
  
    // Gaming Consoles (111–120)
    {
      id: 111,
      brand: 'Sony',
      name: 'PlayStation 5 (PS5)',
      description: 'Next-gen gaming console with 4K support, ultra-fast SSD, and immersive gameplay.',
      price: '₹49,990',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 112,
      brand: 'Microsoft',
      name: 'Xbox Series X',
      description: 'Powerful gaming console with 4K gaming, and support for Ray Tracing.',
      price: '₹49,990',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 113,
      brand: 'Nintendo',
      name: 'Nintendo Switch OLED Model',
      description: 'Hybrid gaming console with vibrant OLED display for enhanced gameplay.',
      price: '₹39,990',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 114,
      brand: 'Razer',
      name: 'Razer Kraken Gaming Headset',
      description: 'Gaming headset with THX Spatial Audio, noise cancellation, and comfortable design.',
      price: '₹7,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 115,
      brand: 'Logitech',
      name: 'Logitech G502 HERO Gaming Mouse',
      description: 'High-precision gaming mouse with customizable RGB lighting and 16K DPI.',
      price: '₹3,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 116,
      brand: 'Corsair',
      name: 'Corsair K95 RGB Platinum Gaming Keyboard',
      description: 'Mechanical keyboard with RGB lighting and Cherry MX switches for precise keystrokes.',
      price: '₹15,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'Limited Stock',
    },
    {
      id: 117,
      brand: 'SteelSeries',
      name: 'SteelSeries Arctis 7 Wireless Gaming Headset',
      description: 'Wireless gaming headset with surround sound, noise-cancelling microphone.',
      price: '₹12,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 118,
      brand: 'Alienware',
      name: 'Alienware AW2521H 24.5" Gaming Monitor',
      description: 'Gaming monitor with 360Hz refresh rate and NVIDIA G-SYNC compatibility.',
      price: '₹51,499',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 119,
      brand: 'Turtle Beach',
      name: 'Turtle Beach Stealth 600 Gen 2 Wireless Headset',
      description: 'Wireless gaming headset with surround sound and comfortable ear cushions.',
      price: '₹8,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 120,
      brand: 'MSI',
      name: 'MSI Optix MAG272C 27" Curved Gaming Monitor',
      description: 'Curved monitor with 165Hz refresh rate and immersive gaming experience.',
      price: '₹19,999',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'Limited Stock',
    },
  
    // Smart Home Devices (121–150)
    {
      id: 121,
      brand: 'Amazon',
      name: 'Echo Dot 4th Gen',
      description: 'Smart speaker with Alexa and enhanced sound quality.',
      price: '₹3,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 122,
      brand: 'Google',
      name: 'Google Nest Mini',
      description: 'Voice-activated speaker with Google Assistant for a smarter home.',
      price: '₹2,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 123,
      brand: 'Philips',
      name: 'Hue White and Color Ambiance Starter Kit',
      description: 'Smart lightbulbs with 16 million colors, controlled by Alexa or Google Assistant.',
      price: '₹8,990',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 124,
      brand: 'TP-Link',
      name: 'Kasa Smart Plug HS100',
      description: 'Smart plug to control any device remotely with the Kasa app or voice assistants.',
      price: '₹1,299',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 125,
      brand: 'Wyze',
      name: 'Wyze Cam v3 Indoor/Outdoor Smart Camera',
      description: '1080p HD security camera with color night vision and two-way audio.',
      price: '₹4,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 126,
      brand: 'Nest',
      name: 'Nest Learning Thermostat',
      description: 'Smart thermostat that learns your schedule and helps save energy.',
      price: '₹24,990',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 127,
      brand: 'Ecobee',
      name: 'Ecobee SmartThermostat with Voice Control',
      description: 'Smart thermostat with built-in Alexa voice control and energy-saving features.',
      price: '₹24,999',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'Limited Stock',
    },
    {
      id: 128,
      brand: 'Philips',
      name: 'Smart Wi-Fi LED Bulb',
      description: 'Smart bulb that changes color and brightness, compatible with Alexa and Google Assistant.',
      price: '₹999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 129,
      brand: 'Ring',
      name: 'Ring Video Doorbell 4',
      description: 'Smart doorbell with HD video, two-way talk, and advanced motion detection.',
      price: '₹10,990',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 130,
      brand: 'Google',
      name: 'Nest Hub Max',
      description: 'Smart display with Google Assistant, ideal for video calls and smart home control.',
      price: '₹22,999',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'Limited Stock',
    },
    
    // Furniture (131–160)
    {
      id: 131,
      brand: 'Urban Ladder',
      name: 'Modern Sofa Set',
      description: 'Comfortable 3-seater sofa set with soft cushions and sleek design.',
      price: '₹29,999',
      deliveryEstimate: '5-8 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 132,
      brand: 'Wakefit',
      name: 'Memory Foam Mattress',
      description: 'High-density memory foam mattress for better sleep and support.',
      price: '₹13,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 133,
      brand: 'HomeTown',
      name: 'Wooden Dining Table Set',
      description: 'Elegant 6-seater dining table made from solid wood with a classic finish.',
      price: '₹24,999',
      deliveryEstimate: '7-10 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 134,
      brand: 'Pepperfry',
      name: 'King-Size Bed with Storage',
      description: 'Spacious king-size bed with under-bed storage for maximum convenience.',
      price: '₹18,999',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 135,
      brand: 'Godrej',
      name: 'Wooden Wardrobe',
      description: 'Durable wooden wardrobe with ample storage space and stylish finish.',
      price: '₹22,499',
      deliveryEstimate: '5-8 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 136,
      brand: 'Furlenco',
      name: 'Sofa Cum Bed',
      description: 'Multi-purpose sofa cum bed perfect for small spaces and guest rooms.',
      price: '₹14,499',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 137,
      brand: 'Durian',
      name: 'Recliner Chair',
      description: 'Comfortable recliner with adjustable backrest and cushioned armrests.',
      price: '₹12,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 138,
      brand: 'Urban Ladder',
      name: 'Coffee Table',
      description: 'Elegant wooden coffee table with sleek design and ample surface area.',
      price: '₹6,999',
      deliveryEstimate: '5-8 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 139,
      brand: 'HomeTown',
      name: 'Office Chair',
      description: 'Ergonomic office chair with adjustable height and lumbar support.',
      price: '₹4,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 140,
      brand: 'Wakefit',
      name: 'Bunk Bed',
      description: 'Space-saving bunk bed with durable structure and safety rails.',
      price: '₹9,999',
      deliveryEstimate: '7-10 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
  
    // Kitchenware (141–170)
    {
      id: 141,
      brand: 'Preethi',
      name: 'Mixer Grinder',
      description: 'Powerful mixer grinder with multiple jars and stainless steel blades.',
      price: '₹3,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 142,
      brand: 'Bajaj',
      name: 'Electric Kettle',
      description: 'Stainless steel electric kettle with automatic shut-off and boil-dry protection.',
      price: '₹1,399',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 143,
      brand: 'Philips',
      name: 'Hand Blender',
      description: 'Cordless hand blender with multiple speed settings for easy blending.',
      price: '₹1,799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 144,
      brand: 'Prestige',
      name: 'Non-Stick Cookware Set (3 Pcs)',
      description: 'Durable non-stick cookware set with soft-touch handles and even heat distribution.',
      price: '₹1,499',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 145,
      brand: 'Tefal',
      name: 'Fry Pan 24 cm',
      description: 'Induction compatible non-stick frying pan with ergonomic handle.',
      price: '₹1,199',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 146,
      brand: 'Crompton',
      name: 'Water Heater',
      description: 'Instant water heater with 5-star energy rating and rust-free body.',
      price: '₹4,199',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 147,
      brand: 'Faber',
      name: 'Kitchen Chimney',
      description: 'Auto-clean chimney with powerful suction and sleek design.',
      price: '₹14,999',
      deliveryEstimate: '5-7 business days',
      returnPolicy: 'Returnable within 15 days.',
      status: 'In Stock',
    },
    {
      id: 148,
      brand: 'Borosil',
      name: 'Microwave Safe Serving Set',
      description: 'Elegant microwave-safe glass serving set with 5 pieces.',
      price: '₹1,599',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 149,
      brand: 'Pigeon',
      name: 'Pressure Cooker',
      description: 'Stainless steel pressure cooker with 3L capacity and safety valve.',
      price: '₹1,199',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 150,
      brand: 'Kenstar',
      name: 'Oven Toaster Grill',
      description: 'Compact OTG with 30L capacity and adjustable temperature settings.',
      price: '₹6,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
  
    // Fashion (151–180)
    {
      id: 151,
      brand: 'Adidas',
      name: 'Ultraboost Running Shoes',
      description: 'Lightweight and comfortable running shoes with responsive cushioning.',
      price: '₹14,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 152,
      brand: 'Nike',
      name: 'Air Max Sneakers',
      description: 'Iconic sneakers with air-cushioned sole for extra comfort.',
      price: '₹11,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 153,
      brand: 'Levi’s',
      name: 'Straight Fit Jeans',
      description: 'Classic straight-fit denim jeans with comfortable stretch fabric.',
      price: '₹2,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 154,
      brand: 'Zara',
      name: 'Cotton T-Shirt',
      description: 'Soft cotton t-shirt with a relaxed fit and stylish design.',
      price: '₹1,199',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 155,
      brand: 'H&M',
      name: 'Printed Hoodie',
      description: 'Warm and trendy hoodie with a stylish graphic print.',
      price: '₹2,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 156,
      brand: 'Van Heusen',
      name: 'Formal Shirt',
      description: 'Elegant formal shirt with a slim fit and premium fabric.',
      price: '₹1,899',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 157,
      brand: 'Puma',
      name: 'Track Pants',
      description: 'Comfortable and breathable track pants with a slim fit.',
      price: '₹1,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 158,
      brand: 'Ray-Ban',
      name: 'Aviator Sunglasses',
      description: 'Classic aviator sunglasses with UV protection and stylish frame.',
      price: '₹5,990',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 159,
      brand: 'Fossil',
      name: 'Men’s Leather Wallet',
      description: 'Premium leather wallet with multiple card slots and coin pocket.',
      price: '₹2,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 160,
      brand: 'Michael Kors',
      name: 'Women’s Handbag',
      description: 'Trendy women’s handbag with spacious compartments and stylish design.',
      price: '₹8,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    
    // Beauty & Personal Care (161–190)
    {
      id: 161,
      brand: 'L’Oréal',
      name: 'Revitalift Face Serum',
      description: 'Anti-aging serum that boosts skin elasticity and reduces wrinkles.',
      price: '₹1,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 162,
      brand: 'Nivea',
      name: 'Body Lotion',
      description: 'Moisturizing body lotion for soft and smooth skin.',
      price: '₹299',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 163,
      brand: 'Maybelline',
      name: 'Fit Me Foundation',
      description: 'Liquid foundation with a natural finish and buildable coverage.',
      price: '₹699',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 164,
      brand: 'Lakmé',
      name: 'Enrich Lip Crayon',
      description: 'Long-lasting lip crayon with vibrant color and smooth application.',
      price: '₹399',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 165,
      brand: 'Gillette',
      name: 'Fusion5 Razor',
      description: 'Precision razor with 5 blades for a smooth and comfortable shave.',
      price: '₹849',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 166,
      brand: 'The Body Shop',
      name: 'Tea Tree Oil',
      description: 'Pure tea tree oil for skin care, acne treatment, and cleansing.',
      price: '₹899',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 167,
      brand: 'Himalaya',
      name: 'Neem Face Wash',
      description: 'Gentle face wash with neem and turmeric for clear and healthy skin.',
      price: '₹199',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 168,
      brand: 'Pond’s',
      name: 'White Beauty Cream',
      description: 'Fairness cream with Vitamin B3 that brightens skin tone.',
      price: '₹349',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 169,
      brand: 'Olay',
      name: 'Total Effects Night Cream',
      description: 'Night cream that fights 7 signs of aging and repairs skin.',
      price: '₹1,299',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 170,
      brand: 'Revlon',
      name: 'Colorstay Eyeliner',
      description: 'Waterproof eyeliner with smudge-proof formula for long-lasting wear.',
      price: '₹699',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
  
    // Kids (170–200)
    {
      id: 170,
      brand: 'LeapFrog',
      name: 'LeapPad Academy Tablet',
      description: 'Educational tablet with preloaded games, videos, and activities for kids aged 3-9.',
      price: '₹10,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 10 days.',
      status: 'In Stock',
    },
    {
      id: 171,
      brand: 'Fisher-Price',
      name: 'Laugh & Learn Smart Stages Chair',
      description: 'Interactive learning chair for toddlers with lights, sounds, and songs to teach numbers and letters.',
      price: '₹4,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 172,
      brand: 'LEGO',
      name: 'LEGO Classic Large Creative Brick Box',
      description: 'Creative set with 790 pieces to build various models and designs.',
      price: '₹3,299',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 173,
      brand: 'Hot Wheels',
      name: 'Hot Wheels Track Builder Set',
      description: 'Customizable track builder set to create challenging and fun racing tracks.',
      price: '₹2,199',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 174,
      brand: 'Barbie',
      name: 'Barbie Dreamhouse Dollhouse',
      description: 'Interactive dollhouse with multiple rooms, furniture, and accessories for Barbie dolls.',
      price: '₹9,499',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 175,
      brand: 'Nerf',
      name: 'Nerf Elite 2.0 Shockwave Blaster',
      description: 'Motorized Nerf blaster that shoots darts up to 90 feet.',
      price: '₹2,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 176,
      brand: 'VTech',
      name: 'VTech KidiZoom Smartwatch DX2',
      description: 'Kid-friendly smartwatch with camera, games, and fitness tracker for kids aged 4-9.',
      price: '₹5,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 177,
      brand: 'Play-Doh',
      name: 'Play-Doh Modeling Compound Set',
      description: 'Colorful set of non-toxic Play-Doh to shape and mold creative figures.',
      price: '₹799',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 178,
      brand: 'Crayola',
      name: 'Crayola 64 Count Crayon Box',
      description: 'Large crayon box with 64 vibrant colors for kids to express creativity.',
      price: '₹699',
      deliveryEstimate: '2-3 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 179,
      brand: 'Monopoly',
      name: 'Monopoly Junior Game',
      description: 'Kid-friendly version of the classic Monopoly board game for ages 5+.',
      price: '₹1,299',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 180,
      brand: 'Disney',
      name: 'Disney Princess Magic Tea Party Game',
      description: 'Interactive tea party game featuring favorite Disney Princesses.',
      price: '₹2,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 181,
      brand: 'Hasbro',
      name: 'Scrabble Junior',
      description: 'Classic word game for kids to build their vocabulary and spelling skills.',
      price: '₹899',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 182,
      brand: 'Playmobil',
      name: 'Playmobil City Action Police Station',
      description: 'Police station set with figures, vehicles, and accessories for imaginative play.',
      price: '₹3,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 183,
      brand: 'Fisher-Price',
      name: 'Fisher-Price Imaginext Batcave',
      description: 'Interactive Batcave playset with Batman and other DC characters.',
      price: '₹4,999',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 184,
      brand: 'Baby Alive',
      name: 'Baby Alive Real Surprises Doll',
      description: 'Interactive doll that eats, drinks, and has various expressions.',
      price: '₹2,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 185,
      brand: 'VTech',
      name: 'VTech Touch & Learn Activity Desk',
      description: 'Interactive desk with various activities that help toddlers learn numbers, letters, and shapes.',
      price: '₹6,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 186,
      brand: 'Mattel',
      name: 'Barbie Fashionista Doll',
      description: 'Fashion doll with trendy clothing and accessories.',
      price: '₹1,299',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 187,
      brand: 'VTech',
      name: 'VTech Sit-to-Stand Learning Walker',
      description: 'Interactive walker for babies that helps with balance and motor skills.',
      price: '₹3,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 188,
      brand: 'Play-Doh',
      name: 'Play-Doh Kitchen Creations Magical Oven',
      description: 'Interactive oven for kids to make Play-Doh food items and bake them.',
      price: '₹1,899',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 189,
      brand: 'LeapFrog',
      name: 'LeapFrog My Own LeapTop',
      description: 'Educational toy laptop with letters, numbers, and learning games.',
      price: '₹2,799',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 190,
      brand: 'Razor',
      name: 'Razor A Kick Scooter',
      description: 'High-quality kick scooter with adjustable handlebars and smooth ride for kids.',
      price: '₹3,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 191,
      brand: 'NERF',
      name: 'NERF Elite Disruptor Blaster',
      description: 'A fast-action blaster that can shoot 6 darts in a row.',
      price: '₹1,499',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 192,
      brand: 'Barbie',
      name: 'Barbie Dream Camper',
      description: 'A Barbie camper with an outdoor lounge, convertible car, and accessories.',
      price: '₹7,499',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 193,
      brand: 'LEGO',
      name: 'LEGO City Space Port',
      description: 'Spaceport playset with astronauts, launch pads, and a shuttle.',
      price: '₹6,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 194,
      brand: 'Playmobil',
      name: 'Playmobil Pirate Ship',
      description: 'Pirate ship with sails, figures, and accessories for creative play.',
      price: '₹4,499',
      deliveryEstimate: '4-6 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 195,
      brand: 'VTech',
      name: 'VTech Spinning & Singing Wheel',
      description: 'Interactive toy with music, lights, and spinning action for babies.',
      price: '₹1,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 196,
      brand: 'Fisher-Price',
      name: 'Fisher-Price Thomas & Friends TrackMaster Set',
      description: 'Battery-powered train set with Thomas the Tank Engine and friends.',
      price: '₹3,999',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 197,
      brand: 'Hot Wheels',
      name: 'Hot Wheels City Mega Garage',
      description: 'Interactive mega garage playset with ramps, cars, and a parking structure.',
      price: '₹5,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 198,
      brand: 'Hasbro',
      name: 'Hasbro Gaming Jenga',
      description: 'Classic Jenga game where players take turns removing blocks without toppling the tower.',
      price: '₹1,199',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 199,
      brand: 'Razor',
      name: 'Razor E100 Electric Scooter',
      description: 'Electric scooter for kids with a top speed of 10 mph and battery-powered ride.',
      price: '₹14,499',
      deliveryEstimate: '3-5 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    },
    {
      id: 200,
      brand: 'Nerf',
      name: 'NERF Ultra One Blaster',
      description: 'NERF Ultra blaster with high-performance darts and maximum distance.',
      price: '₹2,999',
      deliveryEstimate: '2-4 business days',
      returnPolicy: 'Returnable within 7 days.',
      status: 'In Stock',
    }
];
  
module.exports = products;  